force-app/main/default/objects/Product2/fields/Best_Seller_Global__c.field-meta.xml
<CustomField>
    <fullName>Best_Seller_Global__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Best Seller Global</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Best_Seller_In_and_Out__c.field-meta.xml
<CustomField>
    <fullName>Best_Seller_In_and_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Best Seller In and Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Clase__c.field-meta.xml
<CustomField>
    <fullName>Clase__c</fullName>
    <label>Clase</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Subfamilia__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01-Chairs</fullName>
            </value>
            <value>
                <fullName>02-Coffe Tables, Side &amp; End Tables</fullName>
            </value>
            <value>
                <fullName>03-Sofas &amp; Couches</fullName>
            </value>
            <value>
                <fullName>04-Sectional Sofas</fullName>
            </value>
            <value>
                <fullName>05-Loveseats</fullName>
            </value>
            <value>
                <fullName>06-Sofa Beds</fullName>
            </value>
            <value>
                <fullName>07-Benches &amp; Ottomans</fullName>
            </value>
            <value>
                <fullName>08-Accent Chairs &amp; Recliners</fullName>
            </value>
            <value>
                <fullName>09-Console Tables &amp; Sideboards</fullName>
            </value>
            <value>
                <fullName>10-Tv Stands &amp; Entertaiment Centers</fullName>
            </value>
            <value>
                <fullName>11-Storage Furniture</fullName>
            </value>
            <value>
                <fullName>01-Dining Chairs</fullName>
            </value>
            <value>
                <fullName>02-Dining Tables</fullName>
            </value>
            <value>
                <fullName>03-Dining Sets</fullName>
            </value>
            <value>
                <fullName>04-Bar Stools</fullName>
            </value>
            <value>
                <fullName>05-Kitchen Carts &amp; Islands</fullName>
            </value>
            <value>
                <fullName>06-Dining Storage</fullName>
            </value>
            <value>
                <fullName>01-Office Chairs</fullName>
            </value>
            <value>
                <fullName>02-Desks</fullName>
            </value>
            <value>
                <fullName>03-Bookcases</fullName>
            </value>
            <value>
                <fullName>04-Office Storage</fullName>
            </value>
            <value>
                <fullName>01-Closet Storage</fullName>
            </value>
            <value>
                <fullName>02-Shoe Storage</fullName>
            </value>
            <value>
                <fullName>03-Storage Carts &amp; Drawers</fullName>
            </value>
            <value>
                <fullName>04-Storage Bins &amp; Boxes</fullName>
            </value>
            <value>
                <fullName>05-Shelving Units</fullName>
            </value>
            <value>
                <fullName>01-Outdoor Dining Sets</fullName>
            </value>
            <value>
                <fullName>02-Outdoor Seating Sets</fullName>
            </value>
            <value>
                <fullName>03-Outdoor Chairs &amp; Loungers</fullName>
            </value>
            <value>
                <fullName>04-Outdoor Tables</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Producto.recordType-meta.xml
<RecordType>
    <fullName>Producto</fullName>
    <active>true</active>
    <description>Use este tipo de registro para productos</description>
    <label>1-Producto</label>
</RecordType>

force-app/main/default/classes/HighlightProductManager.cls
/**
 * Provides methods for defining if a product should be highlighted
 * Possible highlights are:
 * > New
 * > BestSeller In-n-Out
 * > BestSeller Global
 */
public class HighlightProductManager {
    public static final String PRODUCTO_BASE_RT = 'Producto';
    /** 
     *  Filters 10 newest products which have been created in the last 3 months for each product class  
    */
    public static Map<Id, Boolean> getHighlightedAsNew(){
        Map<Id, Boolean> result = new Map<Id, Boolean>();
        Integer i = 0;
        String previousClass = '';
        for(Product2 p : [SELECT Id,
                                Clase__c
                                FROM Product2
                                WHERE CreatedDate > :Date.today().addMonths(-3)
                                AND RecordType.DeveloperName = :PRODUCTO_BASE_RT
                                ORDER BY Clase__c, CreatedDate DESC]) {
            if(p.Clase__c == previousClass) {
                if (i < 10) {
                    result.put(p.Id, true);
                }
            } else {
                i = 0;
                previousClass = p.Clase__c;
                result.put(p.Id, true);
            }
            i++;
        }
        return result;
    }

    /** 
     *  Builds a map for all the products marked as "Best Seller Global"
    */
    public static Map<Id, Boolean> getBestSellerGlobal(){
        Map<Id, Boolean> result = new Map<Id, Boolean>();
        for(Product2 p : [SELECT Id
                                FROM Product2
                                WHERE RecordType.DeveloperName = :PRODUCTO_BASE_RT
                                AND Best_Seller_Global__c = true]) {
            result.put(p.Id, true);
        }
        return result; 
    }

    /** 
     *  Builds a map for all the products marked as "Best Seller In and Out"
    */
    public static Map<Id, Boolean> getBestSellerInNOut(){
        Map<Id, Boolean> result = new Map<Id, Boolean>();
        for(Product2 p : [SELECT Id
                                FROM Product2
                                WHERE RecordType.DeveloperName = :PRODUCTO_BASE_RT
                                AND Best_Seller_In_and_Out__c = true]) {
            result.put(p.Id, true);
        }
        return result;
    }
}