force-app/main/default/objects/Product2/fields/Clase__c.field-meta.xml
<CustomField>
    <fullName>Clase__c</fullName>
    <label>Clase</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Subfamilia__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01-Chairs</fullName>
            </value>
            <value>
                <fullName>02-Coffe Tables, Side &amp; End Tables</fullName>
            </value>
            <value>
                <fullName>03-Sofas &amp; Couches</fullName>
            </value>
            <value>
                <fullName>04-Sectional Sofas</fullName>
            </value>
            <value>
                <fullName>05-Loveseats</fullName>
            </value>
            <value>
                <fullName>06-Sofa Beds</fullName>
            </value>
            <value>
                <fullName>07-Benches &amp; Ottomans</fullName>
            </value>
            <value>
                <fullName>08-Accent Chairs &amp; Recliners</fullName>
            </value>
            <value>
                <fullName>09-Console Tables &amp; Sideboards</fullName>
            </value>
            <value>
                <fullName>10-Tv Stands &amp; Entertaiment Centers</fullName>
            </value>
            <value>
                <fullName>11-Storage Furniture</fullName>
            </value>
            <value>
                <fullName>01-Dining Chairs</fullName>
            </value>
            <value>
                <fullName>02-Dining Tables</fullName>
            </value>
            <value>
                <fullName>03-Dining Sets</fullName>
            </value>
            <value>
                <fullName>04-Bar Stools</fullName>
            </value>
            <value>
                <fullName>05-Kitchen Carts &amp; Islands</fullName>
            </value>
            <value>
                <fullName>06-Dining Storage</fullName>
            </value>
            <value>
                <fullName>01-Office Chairs</fullName>
            </value>
            <value>
                <fullName>02-Desks</fullName>
            </value>
            <value>
                <fullName>03-Bookcases</fullName>
            </value>
            <value>
                <fullName>04-Office Storage</fullName>
            </value>
            <value>
                <fullName>01-Closet Storage</fullName>
            </value>
            <value>
                <fullName>02-Shoe Storage</fullName>
            </value>
            <value>
                <fullName>03-Storage Carts &amp; Drawers</fullName>
            </value>
            <value>
                <fullName>04-Storage Bins &amp; Boxes</fullName>
            </value>
            <value>
                <fullName>05-Shelving Units</fullName>
            </value>
            <value>
                <fullName>01-Outdoor Dining Sets</fullName>
            </value>
            <value>
                <fullName>02-Outdoor Seating Sets</fullName>
            </value>
            <value>
                <fullName>03-Outdoor Chairs &amp; Loungers</fullName>
            </value>
            <value>
                <fullName>04-Outdoor Tables</fullName>
            </value>
            <value>
                <fullName>01-Resina y Plástico</fullName>
                <isActive>false</isActive>
                <label>01-Resina y Plástico</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/M3Unidad__c.field-meta.xml
<CustomField>
    <fullName>M3Unidad__c</fullName>
    <label>M3 unidad</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca_base</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A-!DEA Garden</fullName>
            </value>
            <value>
                <fullName>AR-ARO (MAKRO ARGENTINA)</fullName>
            </value>
            <value>
                <fullName>B-!DEA Home</fullName>
            </value>
            <value>
                <fullName>C-!DEA Heating &amp; Fan</fullName>
            </value>
            <value>
                <fullName>D-DO BRANDS</fullName>
            </value>
            <value>
                <fullName>E-MEMBERS CHOICE (CITY CLUB)</fullName>
            </value>
            <value>
                <fullName>F-ALLURE (DO BRANDS CITY CLUB)</fullName>
            </value>
            <value>
                <fullName>G-B2COOL (DO BRANDS - CITY CLUB)</fullName>
            </value>
            <value>
                <fullName>H-OUTDOOR TREND (SORIANA)</fullName>
            </value>
            <value>
                <fullName>HE-HEUMAN BRAND (LIVERPOOL)</fullName>
            </value>
            <value>
                <fullName>HL-HOME LINE (CHEDRAUI)</fullName>
            </value>
            <value>
                <fullName>I-HOMESTYLE DESIGN (SORIANA)</fullName>
            </value>
            <value>
                <fullName>J-ROOTS (CENCOSUD)</fullName>
            </value>
            <value>
                <fullName>K-BSAFE (AFALPI)</fullName>
            </value>
            <value>
                <fullName>KE-KERRVILLE (HEB)</fullName>
            </value>
            <value>
                <fullName>KO-KOVA (KOVA FURNITURE)</fullName>
            </value>
            <value>
                <fullName>L-LIVING ACCENTS (ACE)</fullName>
            </value>
            <value>
                <fullName>M-MEMBERS MARK (SAMS)</fullName>
            </value>
            <value>
                <fullName>N-TALA 18 (AFALPI)</fullName>
            </value>
            <value>
                <fullName>O-KREA (CENCOSUD)</fullName>
            </value>
            <value>
                <fullName>OS-OUTDOOR SOLUTIONS (HEB)</fullName>
            </value>
            <value>
                <fullName>P-CLARK GARDEN (HOMESENTRY)</fullName>
            </value>
            <value>
                <fullName>Q-SUNABLE (SAMS)</fullName>
            </value>
            <value>
                <fullName>R-CARREFOUR HOME (CARREFOUR)</fullName>
            </value>
            <value>
                <fullName>S-RED DOT (CASA LEY)</fullName>
            </value>
            <value>
                <fullName>ST-STUK (OFFICE MAX)</fullName>
                <default>true</default>
                <label>ST-STUK (OFFICE MAX)</label>
            </value>
            <value>
                <fullName>T-MAHAIA (LA COMER)</fullName>
            </value>
            <value>
                <fullName>U-MASTER CRAFT (SORIANA)</fullName>
            </value>
            <value>
                <fullName>V-VARIOS ESPECIALES</fullName>
            </value>
            <value>
                <fullName>VI-VIOS (SORIANA)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/MasterboxAltoCm__c.field-meta.xml
<CustomField>
    <fullName>MasterboxAltoCm__c</fullName>
    <label>Master Box 1 (alto cm)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MasterboxAnchoCm__c.field-meta.xml
<CustomField>
    <fullName>MasterboxAnchoCm__c</fullName>
    <label>Master Box 1 (ancho cm)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MasterboxLargoCm__c.field-meta.xml
<CustomField>
    <fullName>MasterboxLargoCm__c</fullName>
    <label>Master Box 1 (largo cm)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MasterboxM3__c.field-meta.xml
<CustomField>
    <fullName>MasterboxM3__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Master Box 1 (CBM)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Subfamilia__c.field-meta.xml
<CustomField>
    <fullName>Subfamilia__c</fullName>
    <label>Subfamilia</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>0-Extra</fullName>
                <isActive>false</isActive>
                <label>0-Extra</label>
            </value>
            <value>
                <fullName>1-Aire Libre</fullName>
                <isActive>false</isActive>
                <label>1-Aire Libre</label>
            </value>
            <value>
                <fullName>1-Back to School y Oficina</fullName>
                <isActive>false</isActive>
                <label>1-Back to School y Oficina</label>
            </value>
            <value>
                <fullName>1-Fans</fullName>
            </value>
            <value>
                <fullName>1-Kids&apos; furniture</fullName>
            </value>
            <value>
                <fullName>1-Living Room Furniture</fullName>
            </value>
            <value>
                <fullName>1-Muebles de Jardín</fullName>
                <isActive>false</isActive>
                <label>1-Muebles de Jardín</label>
            </value>
            <value>
                <fullName>1-Outdoor Furniture</fullName>
            </value>
            <value>
                <fullName>1-Seguridad</fullName>
                <isActive>false</isActive>
                <label>1-Seguridad</label>
            </value>
            <value>
                <fullName>2-Creatividad</fullName>
                <isActive>false</isActive>
                <label>2-Creatividad</label>
            </value>
            <value>
                <fullName>2-Indoor Heaters</fullName>
            </value>
            <value>
                <fullName>2-Kitchen &amp; Dining Furniture</fullName>
            </value>
            <value>
                <fullName>2-Muebles de Comedor y Cocina</fullName>
                <isActive>false</isActive>
                <label>2-Muebles de Comedor y Cocina</label>
            </value>
            <value>
                <fullName>2-Outdoor Shades &amp; Structures</fullName>
            </value>
            <value>
                <fullName>2-Outdoor Toys</fullName>
            </value>
            <value>
                <fullName>2-Outdoor y Temporada</fullName>
                <isActive>false</isActive>
                <label>2-Outdoor y Temporada</label>
            </value>
            <value>
                <fullName>2-Taller</fullName>
                <isActive>false</isActive>
                <label>2-Taller</label>
            </value>
            <value>
                <fullName>3-BBQ</fullName>
                <isActive>false</isActive>
                <label>3-BBQ</label>
            </value>
            <value>
                <fullName>3-Calefacción y Climatización</fullName>
                <isActive>false</isActive>
                <label>3-Calefacción y Climatización</label>
            </value>
            <value>
                <fullName>3-Juegos de Imitación</fullName>
                <isActive>false</isActive>
                <label>3-Juegos de Imitación</label>
            </value>
            <value>
                <fullName>3-Muebles de Sala y Habitación</fullName>
                <isActive>false</isActive>
                <label>3-Muebles de Sala y Habitación</label>
            </value>
            <value>
                <fullName>3-Office Furniture</fullName>
            </value>
            <value>
                <fullName>3-Outdoor Cooking</fullName>
            </value>
            <value>
                <fullName>3-Outdoor Heaters</fullName>
            </value>
            <value>
                <fullName>4-Air Treatment</fullName>
            </value>
            <value>
                <fullName>4-Camping &amp; Beach</fullName>
            </value>
            <value>
                <fullName>4-Equipamiento de Seguridad</fullName>
                <isActive>false</isActive>
                <label>4-Equipamiento de Seguridad</label>
            </value>
            <value>
                <fullName>4-Fans</fullName>
                <isActive>false</isActive>
                <label>4-Fans</label>
            </value>
            <value>
                <fullName>4-Jardinería</fullName>
                <isActive>false</isActive>
                <label>4-Jardinería</label>
            </value>
            <value>
                <fullName>4-Muñecas y Figuras</fullName>
                <isActive>false</isActive>
                <label>4-Muñecas y Figuras</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/UnidadesContainer20__c.field-meta.xml
<CustomField>
    <fullName>UnidadesContainer20__c</fullName>
    <label>Units / 20GP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnidadesHQ__c.field-meta.xml
<CustomField>
    <fullName>UnidadesHQ__c</fullName>
    <label>Units / 40HQ</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnidadesPorMasterBox__c.field-meta.xml
<CustomField>
    <fullName>UnidadesPorMasterBox__c</fullName>
    <label>Units per Master Box 1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Producto.recordType-meta.xml
<RecordType>
    <fullName>Producto</fullName>
    <active>true</active>
    <description>Use este tipo de registro para productos</description>
    <label>1-Producto</label>
</RecordType>

force-app/main/default/classes/TestHighlightProductManager.cls
@isTest
private class TestHighlightProductManager {
    
    @TestSetup
    static void makeData(){
        String marcaValue;
        String marcaValueUpper;
        String familyValue;
        String familyValueUpper;
        
        String marcaProductoGarden;        
        String marcaProductoOutdoorSoriana;
        String familyProductoGarden;
        
        Schema.DescribeFieldResult fieldResult;
        List<Schema.PicklistEntry> ple;
        
        TestUtil tu = new TestUtil();
        tu.initSoloBase();

        fieldResult = Product2.Marca__c.getDescribe();
        ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple) {
            marcaValue = pickListVal.getLabel();
            marcaValueUpper = marcaValue.toUpperCase();
            if(marcaValueUpper.contains('GARDEN')) {
                marcaProductoGarden = marcaValue;
            }
            if(marcaValueUpper.contains('OUTDOOR') && marcaValueUpper.contains('SORIANA')) {
                marcaProductoOutdoorSoriana = marcaValue;
            }
        }


        fieldResult = Product2.Family.getDescribe();
        ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple) {
            familyValue = pickListVal.getLabel();
            familyValueUpper = familyValue.toUpperCase();
            if(familyValueUpper.contains('GARDEN')) {
                familyProductoGarden = familyValue;
            }
        }

        Id prodRTId = Schema.SObjectType.Product2.getRecordTypeInfosByDeveloperName().get('Producto').getRecordTypeId();
        List<Product2> productosBase = new List<Product2>();
        for(Integer i = 0; i < 4; i++){
            productosBase.add(new Product2(Name = i == 0 ? 'Chair' : 'Sofa ' + String.valueOf(i),
                                        RecordTypeId = prodRTId, 
                                        M3Unidad__c = 0.5,
                                        UnidadesPorMasterBox__c = 2,
                                        UnidadesHQ__c = 1000,
                                        UnidadesContainer20__c = 400,
                                        isActive = false,
                                        MasterboxAltoCm__c = i == 0 ? '100' : '10',
                                        MasterboxAnchoCm__c = i == 0 ? '100' : '10',
                                        MasterboxLargoCm__c = i == 0 ? '100' : '10',
                                        MasterboxM3__c = i == 0 ? 1 : 0.001,
                                        Family = familyProductoGarden,
                                        Subfamilia__c = '1-Muebles de Jardín',
                                        Clase__c = '01-Resina y Plástico',
                                        Marca__c = marcaProductoGarden,
                                        Packaging__c = i == 0 ? '1-CAJA MARRON' : '9-CAJA COLOR',
                                        Listado_en_Catalogo__c = true,
                                        Best_Seller_Global__c = i == 0 ? true : false));
        }
        insert productosBase;
    }

    @isTest
    static void TestAllMethods() {
        Map<Id, Boolean> results = HighlightProductManager.getHighlightedAsNew();
        system.assertEquals(results.size(), 6); //Accounts for the two products created in TestUtil InitSoloBase
        results = HighlightProductManager.getBestSellerGlobal();
        system.assertEquals(results.size(), 1);
        results = HighlightProductManager.getBestSellerInNOut();
        system.assertEquals(results.size(), 0);
    }
}