force-app/main/default/objects/Product2/fields/CodigoDeProductoBase__c.field-meta.xml
<CustomField>
    <fullName>CodigoDeProductoBase__c</fullName>
    <formula>IF ( RecordType.Name = &quot;2-Producto de Fábrica&quot; ,
ProductoBase__r.ProductCode ,
IF ( RecordType.Name = &quot;3-Opción de Packaging&quot; ,
ProductoDeFabrica__r.ProductoBase__r.ProductCode ,
ProductCode
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código de producto base (**)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Descripcion_Larga__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Larga__c</fullName>
    <formula>Name + &apos; &apos; + Color2__c + &apos; &apos; + Medidas_del_Producto_Agrupadas2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Descripción Larga</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Estado_verificacion_costo__c.field-meta.xml
<CustomField>
    <fullName>Estado_verificacion_costo__c</fullName>
    <label>Estado verificación costo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En Proceso</fullName>
            </value>
            <value>
                <fullName>Verificado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Fabrica__c.field-meta.xml
<CustomField>
    <fullName>Fabrica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fábrica</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La cuenta de proveedor no existe o no es una fábrica.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Proveedor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Productos de la fábrica</relationshipLabel>
    <relationshipName>ProductosDeLaFabrica</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Fecha_revision_costo__c.field-meta.xml
<CustomField>
    <fullName>Fecha_revision_costo__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Fecha en la que se hizo la última revision del costo a este producto</description>
    <label>Fecha última revision costo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IDImagen1__c.field-meta.xml
<CustomField>
    <fullName>IDImagen1__c</fullName>
    <label>ID Imagen 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Imagen1__c.field-meta.xml
<CustomField>
    <fullName>Imagen1__c</fullName>
    <formula>IMAGE(&apos;/servlet/servlet.FileDownload?file=&apos; + 
  IF(OR(RecordType.DeveloperName == &apos;Producto&apos;,
        RecordType.DeveloperName == &apos;Prospecto_de_Producto&apos;)
            &amp;&amp; NOT(ISBLANK(IDImagen1__c)),
    IDImagen1__c,
    IF(RecordType.DeveloperName == &apos;ProductoDeFabrica&apos; &amp;&amp; NOT(ISBLANK(ProductoBase__r.IDImagen1__c)),
    ProductoBase__r.IDImagen1__c,
    IF(NOT(ISBLANK(ProductoDeFabrica__r.ProductoBase__r.IDImagen1__c)),
    ProductoDeFabrica__r.ProductoBase__r.IDImagen1__c,
    &apos;0154w0000242U1s&apos;)))
, Name , 150, 150)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Imagen 1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Precio_Vigente__c.field-meta.xml
<CustomField>
    <fullName>Precio_Vigente__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determina si el precio de este producto es vigente respecto al plazo de vigencia de la fábrica</description>
    <label>Precio Vigente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/PrecioDeFabrica__c.field-meta.xml
<CustomField>
    <fullName>PrecioDeFabrica__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Precio de fabrica (no incluye costos de importación)</description>
    <label>Costo Fábrica</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductoBase__c.field-meta.xml
<CustomField>
    <fullName>ProductoBase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto base</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El producto no existe o no es un producto base.</errorMessage>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>1-Producto</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Fábricas del producto</relationshipLabel>
    <relationshipName>FabricasDelProducto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Thumb1__c.field-meta.xml
<CustomField>
    <fullName>Thumb1__c</fullName>
    <formula>IF(
OR(NOT(ISBLANK(IDImagen1__c)),
NOT(ISBLANK(ProductoBase__r.IDImagen1__c)),
NOT(ISBLANK(ProductoDeFabrica__r.ProductoBase__r.IDImagen1__c))),

IMAGE(&apos;/servlet/servlet.FileDownload?file=&apos; + 
  IF( OR(RecordType.DeveloperName == &apos;Producto&apos;,
        RecordType.DeveloperName == &apos;Prospecto_de_Producto&apos;),
    IDImagen1__c,
    IF(RecordType.DeveloperName == &apos;ProductoDeFabrica&apos;,
    ProductoBase__r.IDImagen1__c,
    ProductoDeFabrica__r.ProductoBase__r.IDImagen1__c))
, Name , 75, 75),

IMAGE(&apos;/servlet/servlet.FileDownload?file=015460000005lAl&apos;, &apos;No Disponible&apos;, 75, 75))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Thumb 1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/ProductoDeFabrica.recordType-meta.xml
<RecordType>
    <fullName>ProductoDeFabrica</fullName>
    <active>true</active>
    <description>Use este tipo de registro para los productos producidos por una fábrica</description>
    <label>2-Producto de Fábrica</label>
</RecordType>

force-app/main/default/classes/VencimientoCostosController.cls
public class VencimientoCostosController {
    public List<VencimientoCostoProduct> productsVC {set; get;}
    public List<VencimientoCostoProduct> prodsToVerify;    

    public VencimientoCostosController() {
        getProducts();
    }


    public void getProducts() {
        System.debug('GPPPPP');
        List<Product2> products;
        productsVC = new List<VencimientoCostoProduct>();
        VencimientoCostoProduct productVC;
        Integer consecutive = 0;
        List<Verificacion_Costo_Productos__c> listVCP;
        Map<String, String> mapProdEstado;
        String estadoV;

        mapProdEstado = new Map<String, String>();

        products = [SELECT Id,
                           Name,
                           CodigoDeProductoBase__c,
                           ProductCode,
                           PrecioDeFabrica__c,
                           Fecha_revision_costo__c,
                           Estado_verificacion_costo__c,
                           Precio_Vigente__c,
                           ProductoBase__r.Descripcion_Larga__c,
                           ProductoBase__r.IDImagen1__c,
                           ProductoBase__r.Imagen1__c,
                           ProductoBase__r.Thumb1__c,
                           ProductoBase__r.ProductCode,
                           Fabrica__c,
                           Fabrica__r.Name,
                           Fabrica__r.Plazo_Precios_Proveedor__c
                      FROM Product2
                     WHERE isActive = true
                       AND RecordType.DeveloperName = 'ProductoDeFabrica'                     
                       AND CodigoDeProductoBase__c != '22222222' LIMIT 1000];
                       
                       
        listVCP = [SELECT Id, 
                          Product__c, 
                          Estado__c 
                     FROM Verificacion_Costo_Productos__c 
                    WHERE Estado__c != 'Aprobado'];
                    
        for(Verificacion_Costo_Productos__c vcp : listVCP) {
            mapProdEstado.put(vcp.Product__c, vcp.Estado__c);
        }

        for(Product2 p : products) {
            productVC = new VencimientoCostoProduct(p);
            estadoV = mapProdEstado.get(p.Id);

            //System.debug(' diasVnc [' + productVC.diasVencimiento + ']');
            if (productVC.diasVencimiento <= 15) {
                if(estadoV == null) {
                    consecutive++;
                    productVC.numberRow = consecutive;
                    productsVC.add(productVC);
                }
            }
        }
        
        productsVC.sort();

        System.debug('sz [' + productsVC.size() + ']');
    }



    public PageReference verification() {
        PageReference pageRef = new PageReference('/lightning/o/Opportunity/list');
        prodsToVerify = new List<VencimientoCostoProduct>();

        for(VencimientoCostoProduct pcv : productsVC) {
            if(!pcv.isPrecioVigente) {
                prodsToVerify.add(pcv);
            }
        }
        saveVerification(prodsToVerify);
        return pageRef;
    }

    public PageReference manualVerification() {
        PageReference pageRef = new PageReference('/lightning/o/Opportunity/list');
        prodsToVerify = new List<VencimientoCostoProduct>();

        for(VencimientoCostoProduct pcv : productsVC) {
            if(pcv.isMarkedForVerification) {
                prodsToVerify.add(pcv);
            }
        }

        saveVerification(prodsToVerify);
        return pageRef;
    }


    public PageReference factoryVerification() {
        VencimientoCostoProduct vcpSelected;
        PageReference pageRef = new PageReference('/lightning/o/Opportunity/list');
        prodsToVerify = new List<VencimientoCostoProduct>();

        for(VencimientoCostoProduct pcv : productsVC) {
            if(pcv.isMarkedForVerification) {
               vcpSelected = pcv;
               break;
            }
        }
        
        if(vcpSelected != null) {
            for(VencimientoCostoProduct pcv : productsVC) {
                if(pcv.product.Fabrica__r.Name != null && vcpSelected.product.Fabrica__r.Name != null) {
                    if(pcv.product.Fabrica__r.Name.equals(vcpSelected.product.Fabrica__r.Name)) {
                        prodsToVerify.add(pcv);                    
                    }
                }
            }
        }

        saveVerification(prodsToVerify);
        return pageRef;
    }


    private void saveVerification(List<VencimientoCostoProduct> pdsToVerify) {
        Verificacion_Costo__c vc;
        List<Verificacion_Costo_Productos__c> vcpList;
        Verificacion_Costo_Productos__c vcp;

        vc = new Verificacion_Costo__c(Name = 'PROD-' + Date.today(),
                                       Estado__c = 'En Verificacion');
        
        insert vc;

        vcpList = new List<Verificacion_Costo_Productos__c>();

        for(VencimientoCostoProduct pvc : pdsToVerify) {
            vcp = new Verificacion_Costo_Productos__c(Verificacion_Costo__c = vc.Id,
                                                      Estado__c = 'Pendiente',
                                                      Fecha_Estado__c = Date.today(),
                                                      Factory__c  = pvc.product.fabrica__c,
                                                      Product__c = pvc.product.Id);
            vcpList.add(vcp);                                        
        }

        insert vcpList;
    }
    
}