force-app/main/default/objects/Product2/fields/Codigo_DUN_14__c.field-meta.xml
<CustomField>
    <fullName>Codigo_DUN_14__c</fullName>
    <label>Código DUN 14</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Codigo_EAN__c.field-meta.xml
<CustomField>
    <fullName>Codigo_EAN__c</fullName>
    <label>Código EAN</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <formula>IF(IsActive,
   IF(TEXT($User.LanguageLocaleKey) = &quot;en_US&quot;, &quot;Primary&quot;, &quot;Principal&quot;),
   IF(TEXT($User.LanguageLocaleKey) = &quot;en_US&quot;, &quot;Alternative&quot;, &quot;Alternativa&quot;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estatus</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Listado_en_catalogo__c.field-meta.xml
<CustomField>
    <fullName>Listado_en_catalogo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si el Producto debe ser listado en el catalogo web y en la pagina de agregar productos a oportunidad. Usado para evitar que aparezca varias veces el mismo producto con distinta marca</description>
    <inlineHelpText>Indicates whether the product should be listed in the web catalog and on the add products page</inlineHelpText>
    <label>Listado en catálogo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca_base</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A-!DEA Garden</fullName>
            </value>
            <value>
                <fullName>AR-ARO (MAKRO ARGENTINA)</fullName>
            </value>
            <value>
                <fullName>B-!DEA Home</fullName>
            </value>
            <value>
                <fullName>C-!DEA Heating &amp; Fan</fullName>
            </value>
            <value>
                <fullName>D-DO BRANDS</fullName>
            </value>
            <value>
                <fullName>E-MEMBERS CHOICE (CITY CLUB)</fullName>
            </value>
            <value>
                <fullName>F-ALLURE (DO BRANDS CITY CLUB)</fullName>
            </value>
            <value>
                <fullName>G-B2COOL (DO BRANDS - CITY CLUB)</fullName>
            </value>
            <value>
                <fullName>H-OUTDOOR TREND (SORIANA)</fullName>
            </value>
            <value>
                <fullName>HE-HEUMAN BRAND (LIVERPOOL)</fullName>
            </value>
            <value>
                <fullName>HL-HOME LINE (CHEDRAUI)</fullName>
            </value>
            <value>
                <fullName>I-HOMESTYLE DESIGN (SORIANA)</fullName>
            </value>
            <value>
                <fullName>J-ROOTS (CENCOSUD)</fullName>
            </value>
            <value>
                <fullName>K-BSAFE (AFALPI)</fullName>
            </value>
            <value>
                <fullName>KE-KERRVILLE (HEB)</fullName>
            </value>
            <value>
                <fullName>KO-KOVA (KOVA FURNITURE)</fullName>
            </value>
            <value>
                <fullName>L-LIVING ACCENTS (ACE)</fullName>
            </value>
            <value>
                <fullName>M-MEMBERS MARK (SAMS)</fullName>
            </value>
            <value>
                <fullName>N-TALA 18 (AFALPI)</fullName>
            </value>
            <value>
                <fullName>O-KREA (CENCOSUD)</fullName>
            </value>
            <value>
                <fullName>OS-OUTDOOR SOLUTIONS (HEB)</fullName>
            </value>
            <value>
                <fullName>P-CLARK GARDEN (HOMESENTRY)</fullName>
            </value>
            <value>
                <fullName>Q-SUNABLE (SAMS)</fullName>
            </value>
            <value>
                <fullName>R-CARREFOUR HOME (CARREFOUR)</fullName>
            </value>
            <value>
                <fullName>S-RED DOT (CASA LEY)</fullName>
            </value>
            <value>
                <fullName>ST-STUK (OFFICE MAX)</fullName>
                <default>true</default>
                <label>ST-STUK (OFFICE MAX)</label>
            </value>
            <value>
                <fullName>T-MAHAIA (LA COMER)</fullName>
            </value>
            <value>
                <fullName>U-MASTER CRAFT (SORIANA)</fullName>
            </value>
            <value>
                <fullName>V-VARIOS ESPECIALES</fullName>
            </value>
            <value>
                <fullName>VI-VIOS (SORIANA)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductoBase__c.field-meta.xml
<CustomField>
    <fullName>ProductoBase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto base</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El producto no existe o no es un producto base.</errorMessage>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>1-Producto</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Fábricas del producto</relationshipLabel>
    <relationshipName>FabricasDelProducto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CloneProduct.cls
/**
*   Controller for CloneProduct page
*   @version    1.0
*   @author lcosta@infolastic.com
 */
public class CloneProduct {
  
    private Product2 originalProduct; 
    private set<String> fieldNames;
    public List<SelectOption> altBrands {get;set;}
    public String newBrand {get;set;}
    public String newColor {get;set;}

    public Boolean modifyBrand{get;set;}
    public Boolean modifyColor{get;set;}

    public static final String COLOR_EMPTY = 'Debe especificar un color';
    public static final String SAME_COLOR = 'Debe especificar un color diferente al original';

    public Boolean newBrandEnabled {get;set;}
    public Boolean newColorEnabled {get;set;}

    public CloneProduct(ApexPages.StandardController std) {
        modifyBrand = false;
        modifyColor = false;
        Map<String, Schema.SObjectField> fieldMap = Product2.sObjectType.getDescribe().fields.getMap();
        fieldNames = fieldMap.keySet();
        List<Product2> pro = Database.query('SELECT ' + String.join((Iterable<String>)fieldNames, ',') 
                                            + ' FROM Product2'
                                            + ' WHERE Id = \'' + std.getId() + '\'');
        originalProduct = pro[0];

        //Setup alternative brand options
        altBrands = new List<SelectOption>();
    Schema.DescribeFieldResult fieldResult = Product2.Marca__c.getDescribe();
    List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
    for( Schema.PicklistEntry pickListVal : ple){
      if(pickListVal.getLabel() != originalProduct.Marca__c){
                altBrands.add(new SelectOption(pickListVal.getLabel(), pickListVal.getLabel()));
            }
    }
    
    Clone_Products__c cp = Clone_Products__c.getInstance(); //Configuracion personalizada
    newBrandEnabled = cp.Clone_Brand__c;
    newColorEnabled = cp.Clone_Color__c;
  }

    public PageReference cloneWithFactory() {
        String[] tokens;
        Product2 newClone = originalProduct.clone();
        try{    
            if(modifyBrand){
                newClone.Marca__c = newBrand;
                
                System.debug('new brand [' + newClone.Marca__c + ']');

                System.debug('new pcode orig[' + newClone.ProductCode + ']');
                
                String[] tokensCadena = newClone.ProductCode.split('[0-9]+');
                
                System.debug('size [' + tokensCadena.size() + '] tokensCadena: ' + tokensCadena);
                
                String tokenFinal = tokensCadena[1];
                Integer sizeTokenFinal = tokenFinal.length();
                
                System.debug('sizeTokenFinal [' + sizeTokenFinal + ']');
                
                //newClone.ProductCode = newClone.ProductCode.subString(0, newClone.ProductCode.length() - 1);
                newClone.ProductCode = newClone.ProductCode.subString(0, newClone.ProductCode.length() - sizeTokenFinal);
                
                System.debug('new pcode [' + newClone.ProductCode + ']');
                
                tokens = newBrand.split('-');
                newClone.ProductCode += tokens[0];
                
                System.debug('new pcode new brand [' + newClone.ProductCode + ']');
            }else if(modifyColor){
                if(newColor == null){
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, COLOR_EMPTY));
                    return null;
                }else if(newColor == originalProduct.Color__c){
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, SAME_COLOR));
                    return null;
                }
                newClone.Color__c = newColor;
                newClone.ProductCode = null;
            }
            
            System.debug('new clone code [' + newClone.ProductCode + ']');
            
            newClone.Codigo_EAN__c = null;
            newClone.Codigo_DUN_14__c = null;
            newClone.Listado_en_Catalogo__c = false;
            insert newClone;

            list<Product2> mainFactory = Database.query('SELECT ' + String.join((Iterable<String>)fieldNames, ',') 
                                                + ' FROM Product2'
                                                + ' WHERE ProductoBase__c = \'' + originalProduct.Id + '\''
                                                + ' AND Estatus__c = \'Principal\''
                                                + ' LIMIT 1');
            if(!mainFactory.isEmpty()){
                Product2 clonedFactory = mainFactory[0].clone();
                clonedFactory.ProductoBase__c = newClone.Id;
                ProductTriggerHelper.resetRunForTesting();
                insert clonedFactory; 
            }
        }catch(DMLException e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getDMLMessage(0)));
            return null;
        }
        return new PageReference('/lightning/r/Product2/' + newClone.Id + '/view');
    }

    public void setMBrand(){
        modifyBrand = true;
    }
    public void setMColor(){
        modifyColor = true;
    }

}