force-app/main/default/objects/Product2/fields/Codigo_Proveedor__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Proveedor__c</fullName>
    <label>Código Proveedor</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CostoPackaging__c.field-meta.xml
<CustomField>
    <fullName>CostoPackaging__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Costo Packaging</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Fabrica__c.field-meta.xml
<CustomField>
    <fullName>Fabrica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fábrica</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La cuenta de proveedor no existe o no es una fábrica.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Proveedor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Productos de la fábrica</relationshipLabel>
    <relationshipName>ProductosDeLaFabrica</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MOQ__c.field-meta.xml
<CustomField>
    <fullName>MOQ__c</fullName>
    <label>MOQ</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Packaging__c.field-meta.xml
<CustomField>
    <fullName>Packaging__c</fullName>
    <label>Packaging</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1-BROWN BOX</fullName>
            </value>
            <value>
                <fullName>2-BROWN BOX + HANGTAG</fullName>
            </value>
            <value>
                <fullName>3-BROWN BOX + COLOR LABEL</fullName>
            </value>
            <value>
                <fullName>7-WHITE BOX + COLOR LABEL</fullName>
            </value>
            <value>
                <fullName>9-COLOR BOX</fullName>
            </value>
            <value>
                <fullName>11-WINDOW BOX</fullName>
            </value>
            <value>
                <fullName>12-BLISTER</fullName>
            </value>
            <value>
                <fullName>13-STACK</fullName>
            </value>
            <value>
                <fullName>15-PDQ</fullName>
            </value>
            <value>
                <fullName>BOLSA RETRÁCTIL CON ETIQUETA COLOR Y CAJA MÁSTER</fullName>
                <isActive>false</isActive>
                <label>BOLSA RETRÁCTIL CON ETIQUETA COLOR Y CAJA MÁSTER</label>
            </value>
            <value>
                <fullName>CAJA  MASTER + ETIQUETA COLGANTE</fullName>
                <isActive>false</isActive>
                <label>CAJA  MASTER + ETIQUETA COLGANTE</label>
            </value>
            <value>
                <fullName>CAJA + ETIQUETA A COLOR</fullName>
                <isActive>false</isActive>
                <label>CAJA + ETIQUETA A COLOR</label>
            </value>
            <value>
                <fullName>CAJA BLANCA + PEGATINA A COLOR</fullName>
                <isActive>false</isActive>
                <label>CAJA BLANCA + PEGATINA A COLOR</label>
            </value>
            <value>
                <fullName>CAJA BLANCA CON A3 A COLOR</fullName>
                <isActive>false</isActive>
                <label>CAJA BLANCA CON A3 A COLOR</label>
            </value>
            <value>
                <fullName>CAJA BLANCA CON PEGATINA A COLOR</fullName>
                <isActive>false</isActive>
                <label>CAJA BLANCA CON PEGATINA A COLOR</label>
            </value>
            <value>
                <fullName>CAJA BLANCA CON STICKER A COLOR</fullName>
                <isActive>false</isActive>
                <label>CAJA BLANCA CON STICKER A COLOR</label>
            </value>
            <value>
                <fullName>CAJA BLANCA ETIQUETA A COLOR</fullName>
                <isActive>false</isActive>
                <label>CAJA BLANCA ETIQUETA A COLOR</label>
            </value>
            <value>
                <fullName>CAJA BLANCA ETIQUETA A COLOR Y HANGTAG</fullName>
                <isActive>false</isActive>
                <label>CAJA BLANCA ETIQUETA A COLOR Y HANGTAG</label>
            </value>
            <value>
                <fullName>CAJA BLANCA SERIFRAFIADA PEGATINA A COLOR HANGTAG</fullName>
                <isActive>false</isActive>
                <label>CAJA BLANCA SERIFRAFIADA PEGATINA A COLOR HANGTAG</label>
            </value>
            <value>
                <fullName>CAJA BLANCA STICKER UNIDAD</fullName>
                <isActive>false</isActive>
                <label>CAJA BLANCA STICKER UNIDAD</label>
            </value>
            <value>
                <fullName>CAJA FULL COLOR</fullName>
                <isActive>false</isActive>
                <label>CAJA FULL COLOR</label>
            </value>
            <value>
                <fullName>CAJA FULL COLOR ETIQUETA COLOR</fullName>
                <isActive>false</isActive>
                <label>CAJA FULL COLOR ETIQUETA COLOR</label>
            </value>
            <value>
                <fullName>CAJA MARRON SERIGRAFIADA
A3 A COLOR</fullName>
                <isActive>false</isActive>
                <label>CAJA MARRON SERIGRAFIADA
A3 A COLOR</label>
            </value>
            <value>
                <fullName>CAJA MARRÓN + A3 A COLOR</fullName>
                <isActive>false</isActive>
                <label>CAJA MARRÓN + A3 A COLOR</label>
            </value>
            <value>
                <fullName>CAJA MARRÓN CON A3 A COLOR</fullName>
                <isActive>false</isActive>
                <label>CAJA MARRÓN CON A3 A COLOR</label>
            </value>
            <value>
                <fullName>CAJA MARRÓN CON ETIQUETA A COLOR IMPRESA</fullName>
                <isActive>false</isActive>
                <label>CAJA MARRÓN CON ETIQUETA A COLOR IMPRESA</label>
            </value>
            <value>
                <fullName>CAJA MARRÓN CON ETIQUETA COLGANTE</fullName>
                <isActive>false</isActive>
                <label>CAJA MARRÓN CON ETIQUETA COLGANTE</label>
            </value>
            <value>
                <fullName>CAJA MARRÓN ETIQUETA HANGTAG</fullName>
                <isActive>false</isActive>
                <label>CAJA MARRÓN ETIQUETA HANGTAG</label>
            </value>
            <value>
                <fullName>CAJA MARRÓN SERIGRAFIADA</fullName>
                <isActive>false</isActive>
                <label>CAJA MARRÓN SERIGRAFIADA</label>
            </value>
            <value>
                <fullName>CAJA MARRÓN STICKER A COLOR</fullName>
                <isActive>false</isActive>
                <label>CAJA MARRÓN STICKER A COLOR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/PlazoDeFabricacion__c.field-meta.xml
<CustomField>
    <fullName>PlazoDeFabricacion__c</fullName>
    <label>Plazo de fabricación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PlazoEnDias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/PrecioDeFabrica__c.field-meta.xml
<CustomField>
    <fullName>PrecioDeFabrica__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Precio de fabrica (no incluye costos de importación)</description>
    <label>Costo Fábrica</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductoBase__c.field-meta.xml
<CustomField>
    <fullName>ProductoBase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto base</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El producto no existe o no es un producto base.</errorMessage>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>1-Producto</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Fábricas del producto</relationshipLabel>
    <relationshipName>FabricasDelProducto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Prospecto_de_Producto.recordType-meta.xml
<RecordType>
    <fullName>Prospecto_de_Producto</fullName>
    <active>true</active>
    <description>Para uso en las Ferias</description>
    <label>Prospecto de Producto</label>
</RecordType>

force-app/main/default/classes/TestBatchPortalProductNotification.cls
@isTest
private class TestBatchPortalProductNotification {
    @isTest
    private static void testNotifications() {
        TestUtil tu = new TestUtil();
        tu.initOpportunityTest();
        Id idRT = Schema.sObjectType.Product2.getRecordTypeInfosByDeveloperName().get('Prospecto_de_Producto').getRecordTypeId();
        Product2 productoProspecto = new Product2(RecordTypeId = idRT,
                                                            ProductoBase__c = tu.productosBase[0].Id,
                                                            Fabrica__c = tu.fabrica.Id,
                                                            Name = '[Providers Portal] Test Product',
                                                            PrecioDeFabrica__c = 1000,
                                                            Codigo_Proveedor__c = 'T-800',
                                                            Packaging__c = '1-CAJA MARRON',
                                                            MOQ__c = 5000,
                                                            CostoPackaging__c = 0,
                                                            PlazoDeFabricacion__c = '30-45 días');
        
        /*This commented lines should not be commented and the Test.isRuningTest condition in the 
        BatchPortalProductNotification class should be removed, but for some strange reason
        the portal Guest User fails to create a product within the test class but manages to do so in the portal */
        //system.runAs(portalGuest) {
            insert productoProspecto;
        //}
        test.startTest();
        BatchPortalProductNotification nb = new BatchPortalProductNotification();
        String schedId = Database.executeBatch(nb);
        test.stopTest();
    }

}