force-app/main/default/objects/Product2/fields/CodigoDeProductoBase__c.field-meta.xml
<CustomField>
    <fullName>CodigoDeProductoBase__c</fullName>
    <formula>IF ( RecordType.Name = &quot;2-Producto de Fábrica&quot; ,
ProductoBase__r.ProductCode ,
IF ( RecordType.Name = &quot;3-Opción de Packaging&quot; ,
ProductoDeFabrica__r.ProductoBase__r.ProductCode ,
ProductCode
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código de producto base (**)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Descripcion_Larga__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Larga__c</fullName>
    <formula>Name + &apos; &apos; + Color2__c + &apos; &apos; + Medidas_del_Producto_Agrupadas2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Descripción Larga</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca_base</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A-!DEA Garden</fullName>
            </value>
            <value>
                <fullName>AR-ARO (MAKRO ARGENTINA)</fullName>
            </value>
            <value>
                <fullName>B-!DEA Home</fullName>
            </value>
            <value>
                <fullName>C-!DEA Heating &amp; Fan</fullName>
            </value>
            <value>
                <fullName>D-DO BRANDS</fullName>
            </value>
            <value>
                <fullName>E-MEMBERS CHOICE (CITY CLUB)</fullName>
            </value>
            <value>
                <fullName>F-ALLURE (DO BRANDS CITY CLUB)</fullName>
            </value>
            <value>
                <fullName>G-B2COOL (DO BRANDS - CITY CLUB)</fullName>
            </value>
            <value>
                <fullName>H-OUTDOOR TREND (SORIANA)</fullName>
            </value>
            <value>
                <fullName>HE-HEUMAN BRAND (LIVERPOOL)</fullName>
            </value>
            <value>
                <fullName>HL-HOME LINE (CHEDRAUI)</fullName>
            </value>
            <value>
                <fullName>I-HOMESTYLE DESIGN (SORIANA)</fullName>
            </value>
            <value>
                <fullName>J-ROOTS (CENCOSUD)</fullName>
            </value>
            <value>
                <fullName>K-BSAFE (AFALPI)</fullName>
            </value>
            <value>
                <fullName>KE-KERRVILLE (HEB)</fullName>
            </value>
            <value>
                <fullName>KO-KOVA (KOVA FURNITURE)</fullName>
            </value>
            <value>
                <fullName>L-LIVING ACCENTS (ACE)</fullName>
            </value>
            <value>
                <fullName>M-MEMBERS MARK (SAMS)</fullName>
            </value>
            <value>
                <fullName>N-TALA 18 (AFALPI)</fullName>
            </value>
            <value>
                <fullName>O-KREA (CENCOSUD)</fullName>
            </value>
            <value>
                <fullName>OS-OUTDOOR SOLUTIONS (HEB)</fullName>
            </value>
            <value>
                <fullName>P-CLARK GARDEN (HOMESENTRY)</fullName>
            </value>
            <value>
                <fullName>Q-SUNABLE (SAMS)</fullName>
            </value>
            <value>
                <fullName>R-CARREFOUR HOME (CARREFOUR)</fullName>
            </value>
            <value>
                <fullName>S-RED DOT (CASA LEY)</fullName>
            </value>
            <value>
                <fullName>ST-STUK (OFFICE MAX)</fullName>
                <default>true</default>
                <label>ST-STUK (OFFICE MAX)</label>
            </value>
            <value>
                <fullName>T-MAHAIA (LA COMER)</fullName>
            </value>
            <value>
                <fullName>U-MASTER CRAFT (SORIANA)</fullName>
            </value>
            <value>
                <fullName>V-VARIOS ESPECIALES</fullName>
            </value>
            <value>
                <fullName>VI-VIOS (SORIANA)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductoBase__c.field-meta.xml
<CustomField>
    <fullName>ProductoBase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto base</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El producto no existe o no es un producto base.</errorMessage>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>1-Producto</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Fábricas del producto</relationshipLabel>
    <relationshipName>FabricasDelProducto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Thumb1__c.field-meta.xml
<CustomField>
    <fullName>Thumb1__c</fullName>
    <formula>IF(
OR(NOT(ISBLANK(IDImagen1__c)),
NOT(ISBLANK(ProductoBase__r.IDImagen1__c)),
NOT(ISBLANK(ProductoDeFabrica__r.ProductoBase__r.IDImagen1__c))),

IMAGE(&apos;/servlet/servlet.FileDownload?file=&apos; + 
  IF( OR(RecordType.DeveloperName == &apos;Producto&apos;,
        RecordType.DeveloperName == &apos;Prospecto_de_Producto&apos;),
    IDImagen1__c,
    IF(RecordType.DeveloperName == &apos;ProductoDeFabrica&apos;,
    ProductoBase__r.IDImagen1__c,
    ProductoDeFabrica__r.ProductoBase__r.IDImagen1__c))
, Name , 75, 75),

IMAGE(&apos;/servlet/servlet.FileDownload?file=015460000005lAl&apos;, &apos;No Disponible&apos;, 75, 75))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Thumb 1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnidadesContainer20__c.field-meta.xml
<CustomField>
    <fullName>UnidadesContainer20__c</fullName>
    <label>Units / 20GP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnidadesContainer40__c.field-meta.xml
<CustomField>
    <fullName>UnidadesContainer40__c</fullName>
    <label>Units / 40GP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnidadesHQ__c.field-meta.xml
<CustomField>
    <fullName>UnidadesHQ__c</fullName>
    <label>Units / 40HQ</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProductExtensionController.cls
public class ProductExtensionController
{
    public static final String KEY_ACC = 'Key Account';

    public ApexPages.StandardSetController stdCon{get; set;}
    
    // List of products that we get with a query
    private List<Product2> productList;
    
    // Map of products selected with checkbox
    private Map<Id, Boolean> checkedProducts;
    
    // List of full products selected
    private Map<Id, Product2> selectedProducts; 
    
    public String prodSearch {get;set;}
    
    //flags to enable or disable output panel in UI
    public Boolean isEditEnabled {get;set;}
    public Boolean isSearchEnabled {get;set;}
    
    public String idSelectedProd {get;set;}
    
    public String selectedPricebook {get;set;}
    
    private List<OpportunityProductHybrid> hybridProds;
    
    private String opportunityId;
    
    private Opportunity opp;
    
    /*
     *  Initializes the page with a list of 300 products. This limit was applied to avoid viewstate error.
     *  The limit won't affect the operations, since sales executives use keyword search to find the products 
     *  and we don't apply the limit there.
     */
    public ProductExtensionController(ApexPages.StandardController controller) {
        opportunityId = controller.getId();

        opp = [SELECT Id, 
                      Pricebook2Id, 
                      PlanificacionComercial__r.PorcentajeAportaciones__c, 
                      PlanificacionComercial__r.PorcentajeConvenio__c,
                      CurrencyISOCode 
                 FROM Opportunity 
                WHERE Id = :opportunityId];
  
        selectedProducts = new Map<Id, Product2>();
        
        productList = [SELECT Id, 
                            Name,
                            Descripcion_Larga__c, 
                            Thumb1__c, 
                            CodigoDeProductoBase__c, 
                            ProductoBase__r.Marca__c, 
                            ProductoBase__r.unidadescontainer20__c, 
                            ProductoBase__r.unidadescontainer40__c, 
                            ProductoBase__r.unidadeshq__c, 
                            IsActive 
                            FROM Product2 
                            WHERE IsActive = true
                            AND Id IN (SELECT Product2Id FROM PricebookEntry WHERE CurrencyISOCode = :opp.CurrencyISOCode)
                            ORDER BY Descripcion_Larga__c
                            LIMIT 300];

        checkedProducts = new Map<Id, Boolean>();
        convertMapToList(productList, checkedProducts);
        
        stdCon = new ApexPages.StandardSetController(productList);
        stdCon.setPageSize(20);
        
        //KEY ACCOUNT PRICEBOOK MUST EXIST SO NOT CHECKING FOR NULLS HERE
        //NEEDS TO BE UPDATED ONCE WE ADD DIFF PRICEBOOKS FOR DIFF INCOTERMS
        List<Pricebook2> keyAccount = [SELECT Id, 
                                            Name 
                                            FROM Pricebook2
                                            WHERE Name = :KEY_ACC];
        
        isSearchEnabled = true;
        isEditEnabled = false;
        selectedPricebook = keyAccount[0].Id;
    }

    
    public List<Product2> getProductList()
    {
         List<Product2> lista;  
         if(stdCon != null)
         {
             System.debug('GET PL Standard Set Controller size[' + stdCon.getResultSize() + ']');
             lista = (List<Product2>)stdCon.getRecords();
             System.debug('GET PL Standard Set Controller size[' + lista.size() + ']');
             return (List<Product2>)stdCon.getRecords(); 
         }
         else
         {
             productList = new List<Product2>();
             return productList; 
         }
    }
 
    
    public void searchProducts()
    {
        String query, strFilter;

        if(prodSearch != null && (prodSearch).trim() !='')
        {
            strFilter = '((';
            Integer i = 0;
            for(String s : prodSearch.trim().split(' ')){
                if(i > 0){
                    strFilter += ' AND ';
                }
                strFilter += 'Descripcion_Larga__c Like \'%' + s + '%\'';
                i++;
            }
            strFilter += ') OR CodigoDeProductoBase__c Like \'%' + prodSearch.trim() + '%\')';
            
        }

        query = 'SELECT Id, Name, Descripcion_Larga__c, Thumb1__c, CodigoDeProductoBase__c, ProductoBase__r.Marca__c,'
                + ' ProductoBase__r.Unidadescontainer20__c, ProductoBase__r.unidadescontainer40__c,' 
                + ' ProductoBase__r.unidadeshq__c, IsActive FROM Product2 WHERE IsActive = true'
                + ' AND Id IN (SELECT Product2Id FROM PricebookEntry WHERE CurrencyISOCode = \'' + opp.CurrencyISOCode +'\')';
        
        if(strFilter != null)
        {
            query += ' AND ' + strFilter;
        }
        query += ' ORDER BY Descripcion_Larga__c LIMIT 300';

        system.debug('QUERY > ' + query + ' < ');
        productList = Database.query(query);
        convertMapToList(productList, checkedProducts);
        
        Product2 preSelected = null;
        for(Product2 pr : productList)
        {
            preSelected = selectedProducts.get(pr.id);
            if(preSelected != null)
            {
                checkedProducts.put(pr.id, true);
            }
        }
        
        stdCon = new ApexPages.StandardSetController(productList);            
        stdCon.setPageSize(20);
    }
    
    
    public Boolean hasNext 
    { 
        get 
        { 
            if(stdCon != null)
            {
                return stdCon.getHasNext(); 
            }
            return false;
            
        } 
        set; 
    } 

    public Boolean hasPrevious 
    { 
        get 
        { 
            if(stdCon != null)
            {
                return stdCon.getHasPrevious(); 
            }
            return false;
        } 
        set; 
    } 

    public Integer pageNumber 
    { 
        get 
        { 
            if(stdCon != null)
            {
               return stdCon.getPageNumber(); 
            }
            return 0;
        } 
        set; 
    } 

    public void previous() 
    { 
        if(stdCon != null)
        {
            stdCon.previous(); 
        }
    } 

    public void next() 
    { 
        if(stdCon != null)
        {
           stdCon.next(); 
        }
    } 
    
    public Integer getResultSize()
    {
        if(stdCon != null)
        {
           return stdCon.getResultSize();
        }
        return 0;
    }
    
 
    public Map<Id, Boolean> getCheckedProducts()
    {
        return checkedProducts;
    }  
    
    
    public void clickProduct()
    {
        Product2 prod;
        String param = Apexpages.currentPage().getParameters().get('idProd');
        Boolean value;
      
        String idp = param;
      
        value = checkedProducts.get(idp);
        if(value)
        {
            prod = findProductById(idp);
            if(prod != null)
            {
                selectedProducts.put(idp, prod);
            }
        }
        else
        {
            //if exist in selected products
            prod = selectedProducts.get(idp);
            if(prod != null)
            {
                //remove              
                selectedProducts.remove(idp);
            }
        }
    }
    
    public void clickDeleteSelectedProduct()
    {
        String prodId = null;
        //String[] tokens = null;
        Product2 prod;
        String param = Apexpages.currentPage().getParameters().get('idProdDel');
        if(idSelectedProd != null)
        {
            prodId = idSelectedProd;
                
            //if exist in selected products
            prod = selectedProducts.get(prodId);
            if(prod != null)
            {
                //remove      
                selectedProducts.remove(prodId);
            }
            checkedProducts.put(prodId, false);
        }
    }
    
    
    public Product2 findProductById(String id)
    {
        if(productList != null)
        {
          for(Product2 prod : productList)
          {
              if(prod.id.equals(id))
              {
                  return prod;
              }
          }
        }
        return null;
    }
    
    public List<Product2> getSelectedProducts()
    {
       List<Product2> listToDisplay = new List<Product2>();
       Product2 value = null;
       for(String idp : selectedProducts.keySet())
       {
           value = selectedProducts.get(idp);
           listToDisplay.add(value);
       }
       return listToDisplay;
    }
    

    public PageReference nextPage()
    {
        isSearchEnabled = false;
        isEditEnabled = true;        
        
        setupListHybridProducts();
        
        return null;
    }


    public PageReference previousPage()
    {
        isSearchEnabled = true;
        isEditEnabled = false;        
        return null;
    }

    
    /**
     * This method is used in UI in order to setup a map associated to checkboxes 
     */
    private void convertMapToList(List<Product2> listProducts, Map<Id, Boolean> checkedProducts)
    {
       for(Product2 p : productList)
       {
           checkedProducts.put(p.Id, false);
       }
    }
    
    
    /*
     * 
     */    
    public class OpportunityProductHybrid
    {
        public Opportunity oppHybridProd;
        public OpportunityLineItem item {get;set;}
        public Product2 product {get;set;}
        public Decimal priceWDisc {get;set;}
        
        public OpportunityProductHybrid(Id oppId, PricebookEntry pbe, Opportunity opp)
        {
            oppHybridProd = opp;
            
            item = new OpportunityLineItem(OpportunityId = oppId,
                                           PricebookEntryId = pbe.Id,
                                           Quantity = null,
                                           UnitPrice = calculateUnitPrice(pbe.UnitPrice).setScale(2),
                                           Aportaciones_2__c = oppHybridProd.PlanificacionComercial__r.PorcentajeAportaciones__c,
                                           Convenio_2__c = oppHybridProd.PlanificacionComercial__r.PorcentajeConvenio__c);
            priceWDisc = item.UnitPrice;
            product = pbe.Product2; 
        }
        
        
        /**
         * 
         */
        private Decimal calculateUnitPrice(Decimal unitPrice)
        {
           Decimal finalUnitPrice;
           finalUnitPrice = unitPrice / ( 1 - ((oppHybridProd.PlanificacionComercial__r.PorcentajeAportaciones__c + oppHybridProd.PlanificacionComercial__r.PorcentajeConvenio__c)/100));
           return finalUnitPrice;
        }
    }
    
    private void setupListHybridProducts()
    {
        List<PricebookEntry> listPriceBookEntry = null;
        List<String> idsProduct = new List<String>();
        Product2 prod;
        
        OpportunityProductHybrid hybridProd;

        for(String idp : selectedProducts.keySet())
        {
            idsProduct.add(idp);
        }

        listPriceBookEntry = [SELECT Id, 
                                     UnitPrice,
                                     Product2.Id,
                                     Product2.Name,
                                     Product2.Descripcion_Larga__c, 
                                     Product2.Thumb1__c, 
                                     Product2.CodigoDeProductoBase__c, 
                                     Product2.ProductoBase__r.Marca__c, 
                                     Product2.ProductoBase__r.Unidadescontainer20__c, 
                                     Product2.ProductoBase__r.Unidadescontainer40__c, 
                                     Product2.ProductoBase__r.Unidadeshq__c, 
                                     Product2.IsActive 
                                FROM PricebookEntry 
                               WHERE Pricebook2Id = :selectedPricebook 
                                 AND Product2Id IN :idsProduct
                                 AND CurrencyISOCode = :opp.CurrencyISOCode
                                 ORDER BY Product2.Descripcion_Larga__c];

        PriceBook2 priceBook = [SELECT Id, Name from Pricebook2 WHERE Id =:selectedPricebook ];
        
        hybridProds = new List<OpportunityProductHybrid>();
        
        for(PriceBookEntry pbe : listPriceBookEntry)
        {
            hybridProd = new OpportunityProductHybrid(opportunityId, pbe, opp);
            hybridProds.add(hybridProd );
        }
    }
    
    public List<OpportunityProductHybrid> getHybridProducts()
    {
        return hybridProds;
    }
    
    
    public void  saveOppLineItem()
    {
        if(opp.Pricebook2Id == null) {
            opp.Pricebook2Id = selectedPricebook;
            update opp;
        }
        String retUrl;    
        List<OpportunityLineItem> oppList = new List<OpportunityLineItem>();
        for(OpportunityProductHybrid hp : hybridProds)
        {
            if(hp.priceWDisc != hp.item.UnitPrice){
                hp.item.Modificar_precio_manual__c = true;
            }
            oppList.add(hp.item);
        }
        
        try
        {
            insert oppList;
        }
        catch(DmlException e)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getDMLMessage(0)));
        }
    }

    public Boolean hasError { 
        get { 
            return ApexPages.hasMessages();
        }       
    }
    
}