force-app/main/default/objects/Product2/fields/CodigoDeProductoBase__c.field-meta.xml
<CustomField>
    <fullName>CodigoDeProductoBase__c</fullName>
    <formula>IF ( RecordType.Name = &quot;2-Producto de Fábrica&quot; ,
ProductoBase__r.ProductCode ,
IF ( RecordType.Name = &quot;3-Opción de Packaging&quot; ,
ProductoDeFabrica__r.ProductoBase__r.ProductCode ,
ProductCode
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código de producto base (**)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Descripcion_Larga__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Larga__c</fullName>
    <formula>Name + &apos; &apos; + Color2__c + &apos; &apos; + Medidas_del_Producto_Agrupadas2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Descripción Larga</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Fabrica__c.field-meta.xml
<CustomField>
    <fullName>Fabrica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fábrica</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La cuenta de proveedor no existe o no es una fábrica.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Proveedor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Productos de la fábrica</relationshipLabel>
    <relationshipName>ProductosDeLaFabrica</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/PlazoDeFabricacion__c.field-meta.xml
<CustomField>
    <fullName>PlazoDeFabricacion__c</fullName>
    <label>Plazo de fabricación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PlazoEnDias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductoBase__c.field-meta.xml
<CustomField>
    <fullName>ProductoBase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto base</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El producto no existe o no es un producto base.</errorMessage>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>1-Producto</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Fábricas del producto</relationshipLabel>
    <relationshipName>FabricasDelProducto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LibraProductosCallout.cls
public class LibraProductosCallout extends LibraCallout {

    public LibraProductosCallout(String type) {
        super(type);
    }

    public override String buildPayload(Object param) {
        String[] tokens;
        String aux;
        String payload;
        Product2 prod;
        Product2 prodProv;
        List<Product2> prodToSendLibra;
        ProductBatchLibra pbl;
        LibraProductoPayload prodPayload;
        LibraProductoProveedorPayload proveedorPayload;
        String descripcion = '';

        pbl = (ProductBatchLibra)param;
        prod = pbl.product;

        prodPayload = new LibraProductoPayload();
        prodPayload.codigo_producto = prod.CodigoDeProductoBase__c;
        prodPayload.codigo_empresa = pbl.sociedadIdentifier;
        
        if(prod.Descripcion_Larga__c != null) {
            descripcion = (prod.Descripcion_Larga__c.length() > 50 ? prod.Descripcion_Larga__c.substring(0, 49) : prod.Descripcion_Larga__c);
        }
        
        prodPayload.desc_ventas = descripcion;
        prodPayload.desc_compras = descripcion;

        //prodToSendLibra = prod.FabricasDelProducto__r;
        prodToSendLibra = pbl.baseProducts;
        for(Product2 prodBL : prodToSendLibra) {
           prodProv = prodBL;
           proveedorPayload = new LibraProductoProveedorPayload();
           if(prodProv.Fabrica__r != null) {
               proveedorPayload.codigo_proveedor = prodProv.Fabrica__r.Codigo_rapido__c;
           }
           
           if(proveedorPayload.codigo_proveedor != null) {
               if(prodProv.PlazoDeFabricacion__c != null) {
                   aux = prodProv.PlazoDeFabricacion__c.replace('días','');
                   aux = aux.replace('<','');
                   aux = aux.replace('>','');
                   aux = aux.trim();
                   tokens = aux.split('-');
                   proveedorPayload.aprovi = String.valueOf(tokens[0]);
               } else {
                   proveedorPayload.aprovi = '';
               }
               proveedorPayload.desc_rove = prodProv.Fabrica__r.Description == null ? '' : prodProv.Fabrica__r.Description;
               proveedorPayload.habitua = 'N';
               prodPayload.proveedores.add(proveedorPayload);
           }
        }

        payload = JSON.serialize(prodPayload);

        return payload;        
    }

    public override Object processResponse(String response) {
        return null;
    }

    public override String buildEndpoint() {
        String endpoint;
        endpoint = CS_ENDPOINT + '?' + PARAM_USER + '=' + CS_USER + '&' + PARAM_PWD + '=' + CS_PASS + '&' + PARAM_ALIAS + '=' + CS_ALIAS;
        return endpoint;
    }

}