force-app/main/default/objects/Product2/fields/CodigoDeProductoBase__c.field-meta.xml
<CustomField>
    <fullName>CodigoDeProductoBase__c</fullName>
    <formula>IF ( RecordType.Name = &quot;2-Producto de Fábrica&quot; ,
ProductoBase__r.ProductCode ,
IF ( RecordType.Name = &quot;3-Opción de Packaging&quot; ,
ProductoDeFabrica__r.ProductoBase__r.ProductCode ,
ProductCode
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código de producto base (**)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Descripcion_Larga__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Larga__c</fullName>
    <formula>Name + &apos; &apos; + Color2__c + &apos; &apos; + Medidas_del_Producto_Agrupadas2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Descripción Larga</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Estado_verificacion_costo__c.field-meta.xml
<CustomField>
    <fullName>Estado_verificacion_costo__c</fullName>
    <label>Estado verificación costo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En Proceso</fullName>
            </value>
            <value>
                <fullName>Verificado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Fabrica__c.field-meta.xml
<CustomField>
    <fullName>Fabrica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fábrica</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La cuenta de proveedor no existe o no es una fábrica.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Proveedor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Productos de la fábrica</relationshipLabel>
    <relationshipName>ProductosDeLaFabrica</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Fecha_revision_costo__c.field-meta.xml
<CustomField>
    <fullName>Fecha_revision_costo__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Fecha en la que se hizo la última revision del costo a este producto</description>
    <label>Fecha última revision costo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IDImagen1__c.field-meta.xml
<CustomField>
    <fullName>IDImagen1__c</fullName>
    <label>ID Imagen 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Precio_Vigente__c.field-meta.xml
<CustomField>
    <fullName>Precio_Vigente__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determina si el precio de este producto es vigente respecto al plazo de vigencia de la fábrica</description>
    <label>Precio Vigente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/PrecioDeFabrica__c.field-meta.xml
<CustomField>
    <fullName>PrecioDeFabrica__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Precio de fabrica (no incluye costos de importación)</description>
    <label>Costo Fábrica</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductoBase__c.field-meta.xml
<CustomField>
    <fullName>ProductoBase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto base</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El producto no existe o no es un producto base.</errorMessage>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>1-Producto</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Fábricas del producto</relationshipLabel>
    <relationshipName>FabricasDelProducto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityCostVerification.cls
public class OpportunityCostVerification {
    public String idOpportunity {set; get;}
    public Opportunity opportunity {set; get;}
    public List<Account> factories {set; get;}
    public List<Product2> products {set; get;}
    private Map<String, List<Product2>> factoriesProds; //idFactory, prod
    private Map<String, Account> idsFactories;
    private Map<String, Product2> idsProducts;
    public List<ProductCostVerification> productsCostV;

    public OpportunityCostVerification(Opportunity popp) {
        opportunity = popp;
        idOpportunity = opportunity.Id;
        factoriesProds = new Map<String, List<Product2>>();
        idsFactories = new Map<String, Account>();
        idsProducts = new Map<String, Product2>();
        productsCostV = new List<ProductCostVerification>();
    }

    public void addOppLineItem(OpportunityLineItem oli) {
         Account factory;
         Product2 prod;
         ProductCostVerification pcv;
         List<Product2> prods;
         Integer plazoPrecios;
         Date ultimaFechaRevision;
         Date limiteFechaRevision;
         Integer diffDays;
         
         factory = idsFactories.get(oli.Product2.Fabrica__c);
         if(factory == null) {
             factory = new Account();
             factory.Name = oli.Product2.Fabrica__r.Name;
             factory.Id = oli.Product2.Fabrica__c;
             idsFactories.put(factory.Id, factory);
         }

         prod = idsProducts.get(oli.Product2Id);
         if(prod == null) {
             prod = new Product2();
             prod.Id = oli.Product2Id;
             prod.Name = oli.Product2.Name;
             prod.PrecioDeFabrica__c = oli.Product2.PrecioDeFabrica__c;
             prod.Fecha_revision_costo__c = oli.Product2.Fecha_revision_costo__c;
             prod.Estado_verificacion_costo__c = oli.Product2.Estado_verificacion_costo__c;

             System.debug(' FRC[' + prod.Fecha_revision_costo__c + '] FP[' + oli.Product2.Fabrica__r.Plazo_Precios_Proveedor__c + ']');

             if(prod.Fecha_revision_costo__c == null || oli.Product2.Fabrica__r.Plazo_Precios_Proveedor__c == null) {
                prod.Precio_Vigente__c = false;
                diffDays = 0;
             } else {
                 plazoPrecios = Integer.valueOf(oli.Product2.Fabrica__r.Plazo_Precios_Proveedor__c);
                 ultimaFechaRevision = prod.Fecha_revision_costo__c;
                 limiteFechaRevision = Date.today();
                 limiteFechaRevision = limiteFechaRevision.addDays(plazoPrecios * -1);
                 if(limiteFechaRevision > ultimaFechaRevision) {
                    prod.Precio_Vigente__c = false;
                 } else {
                    prod.Precio_Vigente__c = true;                     
                 }
                 diffDays = Date.today().daysBetween(ultimaFechaRevision.addDays(plazoPrecios));
             }
             //prod.Precio_Vigente__c = oli.Product2.Precio_Vigente__c;
             prod.IDImagen1__c = oli.Product2.ProductoBase__r.IDImagen1__c;

             pcv = new ProductCostVerification(prod);
             pcv.idFactory = oli.Product2.Fabrica__c;
             pcv.compareType = 'greenred';
             pcv.imageInfo = oli.Product2.ProductoBase__r.IDImagen1__c;
             pcv.codigo = oli.Product2.CodigoDeProductoBase__c;
             pcv.plazoPreciosProveedor = oli.Product2.Fabrica__r.Plazo_Precios_Proveedor__c;
             pcv.isPrecioVigente = prod.Precio_Vigente__c;
             if(pcv.isPrecioVigente) {
                 pcv.orderColor = 3;
                 pcv.colorBall = '/resource/1560452910000/greenCircle';
             } else {
                 pcv.orderColor = 1;
                 pcv.colorBall = '/resource/1560452910000/redCircle';
             }
             pcv.oppLineItemID = oli.Id;
             pcv.descripcion = oli.Product2.ProductoBase__r.Descripcion_Larga__c;
             pcv.fechaRevision = oli.Product2.Fecha_revision_costo__c;
             pcv.daysValidCost = diffDays;

             productsCostV.add(pcv);
             idsProducts.put(prod.Id, prod);
         }

         prods = factoriesProds.get(factory.Id);
         if(prods == null) {
             prods = new List<product2>();
             factoriesProds.put(factory.Id, prods);
         }
         prods.add(prod);
    }

}