force-app/main/default/objects/Product2/fields/Fabrica__c.field-meta.xml
<CustomField>
    <fullName>Fabrica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fábrica</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La cuenta de proveedor no existe o no es una fábrica.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Proveedor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Productos de la fábrica</relationshipLabel>
    <relationshipName>ProductosDeLaFabrica</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Fecha_revision_costo__c.field-meta.xml
<CustomField>
    <fullName>Fecha_revision_costo__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Fecha en la que se hizo la última revision del costo a este producto</description>
    <label>Fecha última revision costo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Producto.recordType-meta.xml
<RecordType>
    <fullName>Producto</fullName>
    <active>true</active>
    <description>Use este tipo de registro para productos</description>
    <label>1-Producto</label>
</RecordType>

force-app/main/default/classes/VencimientoCostoProduct.cls
public class VencimientoCostoProduct implements Comparable {
    public Product2 product {set; get;}

    public Date fechaUltimaRevision {set; get;}
    public Integer diasVencimiento {set; get;}
    public Integer numberRow {set; get;}
    public Boolean isMarkedForVerification {set; get;}
    public Boolean isPrecioVigente {set; get;}
    public String msgDescription {set; get;}
    public String estadoVencimientoProducto {set; get;}

    public VencimientoCostoProduct(Product2 pprod) {
        product = pprod;
        msgDescription = '';
        setDays();
    }

    private void setDays() {

        Integer plazoPrecios;
        Date ultimaFechaRevision;
        Date limiteFechaRevision;
        Integer diffDays;

        if(product != null) {

            //System.debug('fr [' + product.Fecha_revision_costo__c + ']');
            if(product.Fabrica__r.Plazo_Precios_Proveedor__c == null) {
                msgDescription = 'La fábrica no tiene plazo';
            }

            if(product.Fecha_revision_costo__c == null) {
                msgDescription = 'Producto no tiene fecha de revisión de costo';
            }

            if(product.Fabrica__r.Plazo_Precios_Proveedor__c != null && product.Fecha_revision_costo__c != null) {
                plazoPrecios = Integer.valueOf(product.Fabrica__r.Plazo_Precios_Proveedor__c);
                ultimaFechaRevision = product.Fecha_revision_costo__c;
                limiteFechaRevision = Date.today();
                limiteFechaRevision = limiteFechaRevision.addDays(plazoPrecios * -1);
                diffDays = Date.today().daysBetween(ultimaFechaRevision.addDays(plazoPrecios));
    
                diasVencimiento = diffDays;
                if(diasVencimiento < 0) {
                    isPrecioVigente = false;
                } else {
                    isPrecioVigente = true;
                }
            } else {
                isPrecioVigente = false;
                diasVencimiento = 0;
            }
            System.debug(' dv [' + diasVencimiento + '] [' + product.ProductCode + ']');
        }
    }
    
    public Integer compareTo(Object compareTo) {
        VencimientoCostoProduct compareToVCProd = (VencimientoCostoProduct)compareTo;

        if (product != null) {
            if(product.Fabrica__c != null) {
                if(product.Fabrica__r.Name != null) {
                    if(product.Fabrica__r.Name > compareToVCProd.product.Fabrica__r.Name) return 1;
                    if(product.Fabrica__r.Name < compareToVCProd.product.Fabrica__r.Name) return -1;
                    if(product.Fabrica__r.Name.equals(compareToVCProd.product.Fabrica__r.Name)) return 0;
                }
            }
        } else {
            return -1;
        }
        return 0;
    }

}